name = "SkillRating"
uuid = "a4748943-f30d-4e73-8df6-5e79d9c4d1d0"
authors = ["Alan Schelten"]
version = "1.0.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
